### ISSUE TITLE
Unable to find an entry point named 'pinvoke_get_string_length'

### ISSUE THREAD

**Issue by JohnOwuor** [libimobiledevice-win32/imobiledevice-net#12]
Unable to find an entry point named 'pinvoke_get_string_length' in DLL 'libimobiledevice'

**Comment by qmfrederik** [comment]
You need to make sure you use our fork of libimobiledevice. It contains some additional methods that we need to make sure we can e.g. correctly free memory.

If you use our NuGet package, make sure you also reference runtime.linux-x64.iMobileDevice-net, runtime.osx-x64.iMobileDevice-net or runtime.win7-x64.iMobileDevice-net

Alternatively, see https://github.com/libimobiledevice-win32/libimobiledevice for the sources, there are also links to AppVeyor builds from which you can download the .dll's if you want. If on Linux, you may have to compile from source. The libimobiledevice packages that ship with your OS won't work.

**Comment by JohnOwuor** [comment]
Thanks for the help. I did manage to get working. But I have another problem, when I try to "unback" a backup, it returns an error message "Could not perform backup protocol version exchange, error code -6".

**Comment by daniel-bluesea** [comment]
i followed @qmfrederik instruction but when trying to install libimobiledevice i get the following error:

"Could not install package 'libimobiledevice.redist 1.2.1.171'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the pack
age does not contain any assembly references or content files that are compatible with that framework."

**Comment by qmfrederik** [comment]
@daniel-bluesea With the latest versions, you should no longer need to install the libimobiledevice.redist nor runtime.*.iMobileDevice-net packages yourself. 

If you still have an issue getting things to work with the latest version (try version 1.2.1-r196), please feel free to open another ticket.
