### ISSUE TITLE
Is there any subset of dlls that are required to load required native libraries?

### ISSUE THREAD

**Issue by PallaviGarg7** [libimobiledevice-win32/imobiledevice-net#120]
Hi,

To work with nuget package, I need to specify a folder other than "win-x86" for loading native libraries (imobiledevice.dll, ideviceactivation.dll). If I copy only these 2 dlls then I receive following error -
 **_System.ComponentModel.Win32Exception (0x80004005): Could not load the library 'imobiledevice' at '...\imobiledevice.dll'. The error code was 126._**

If I copy all the 22 dlls from packages\iMobileDevice-net.1.2.126\runtimes\win-x86\native\ path, then it works.

 I want to know if there is any subset of these dlls that if copied, it will work.

**Desired features:**
1. Detect iOS device connection (before and after loading native libraries)
2. Get name, udid of device
3. Create a tcp connection with device
4. Detect device detachment from system

Thanks & Regards
Pallavi Garg

**Comment by qmfrederik** [comment]
imobiledevice-net has been tested with _all_ binaries in the \native\ folder. That's the only supported configuration.
