### ISSUE TITLE
iDeviceApi.idevice_get_device_list returning iDeviceError.NoDevice with devices connected.

### ISSUE THREAD

**Issue by Broxxar** [libimobiledevice-win32/imobiledevice-net#125]
The provided sample code that produces a list of connected devices is returning `iDeviceError.NoDevice` unexpectedly. I've tried an iPhone 7 (running iOS 11.4) and an iPhone XS (running iOS 12.1.3) connected in different USB ports with different cables (only USB 3 ports if that makes a difference).

Out of curiosity, I also tried running usbmuxd.exe directly which logs:
```
[10:42:51.1571938][3] enabling libimobiledevice logging
[10:42:51.1571938][3] usbmuxd v1.1.1 starting up
[10:42:51.1571938][1] libusb does not support hotplug events
[10:42:51.1571938][2] Could not open device 1-13: Entity not found
[10:42:51.1571938][3] Initialization complete
[10:42:52.1571938][2] Could not open device 1-13: Entity not found
[10:42:53.1571938][2] Could not open device 1-13: Entity not found
```
And then continues to log `Could not open device` until the device is disconnected or the process is killed.

This was using the NuGet package (v1.2.146).

Any idea what's going on? Any setup notes I might have missed?

**Comment by qmfrederik** [comment]
Here's the standard checklist:
- Make sure you have iTunes installed
- Make sure your device is visible in iTunes
- If there's a Trust pop up which appears on your device, make sure to click Trust so the device pairs with your PC.

usbmuxd.exe is not a recommended approach; please use iTunes instead.

**Comment by Broxxar** [comment]
Wow I completely missed that iTunes is a dependency. Damn that's an annoying one, but it makes sense. Thanks for the quick response!
