### ISSUE TITLE
Unback command returns "Could not perform backup protocol version exchange, error code -6"

### ISSUE THREAD

**Issue by JohnOwuor** [libimobiledevice-win32/imobiledevice-net#13]
When I try to "unback" a backup, the application returns an error message "Could not perform backup protocol version exchange, error code -6".

**Comment by qmfrederik** [comment]
Hi @JohnOwuor 

I'm not sure this is specific to the Windows port of libimobiledevice, could you have a look at the upstream libimobiledevice and see if it fails on Linux/macOS as well?

**Comment by JohnOwuor** [comment]
Thanks for the reply, I will have a look at it, then reply.

**Comment by qmfrederik** [comment]
@JohnOwuor This should be fixed in [version 1.2.1-r196](https://www.nuget.org/packages/imobiledevice-net/1.2.1-r196), can you download that version and give it a try?

**Comment by qmfrederik** [comment]
I'm closing this as another user reported this to be working now; if it's not the case feel free to reopen.
