### ISSUE TITLE
Unable to load DLL 'libimobiledevice': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by sledgehammer777** [libimobiledevice-win32/imobiledevice-net#14]
I get this error when trying to run a .NET 4.6 desktop application with the nuget project added.  What am I missing?

**Comment by crabstick-x** [comment]
How did you fix this?

**Comment by qmfrederik** [comment]
Do you have a reference to [runtime.win-x64.iMobileDevice-net](https://www.nuget.org/packages/runtime.win-x64.iMobileDevice-net/1.2.1-r159) or [runtime.win-x86.iMobileDevice-net](https://www.nuget.org/packages/runtime.win-x86.iMobileDevice-net/1.2.1-r159)?

These NuGet packages provide the unmanaged (C-code) dll's that the .NET layer uses so you need to install them.

**Comment by crabstick-x** [comment]
I am still getting the same error after adding that package. I don't know what is wrong?

**Comment by qmfrederik** [comment]
@crabstick-x Can you try to run 

```
NativeLibraries.Load();
```

before using the libimobiledevice API?

**Comment by crabstick-x** [comment]
Yep, it worked but I am getting the error when attempting to run the example code:

`ReadOnlyCollection<string> udids;
int count = 0;

var idevice = LibiMobileDevice.Instance.iDevice;
var lockdown = LibiMobileDevice.Instance.Lockdown;

var ret = idevice.idevice_get_device_list(out udids, ref count);

if (ret == iDeviceError.NoDevice)
{
    // Not actually an error in our case
    return;
}

ret.ThrowOnError();

// Get the device name
foreach (var udid in udids)
{
    iDeviceHandle deviceHandle;
    idevice.idevice_new(out deviceHandle, udid).ThrowOnError();

    LockdownClientHandle lockdownHandle;
    lockdown.lockdownd_client_new_with_handshake(deviceHandle, out lockdownHandle, "Quamotion").ThrowOnError();

    string deviceName;
    lockdown.lockdownd_get_device_name(lockdownHandle, out deviceName).ThrowOnError();

    deviceHandle.Dispose();
    lockdownHandle.Dispose();
}`
