### ISSUE TITLE
x86 lose libeay32.dll

### ISSUE THREAD

**Issue by rackliu** [libimobiledevice-win32/imobiledevice-net#16]
Hello,
When i use  imobiledevice-net  (Version 1.2.1-r189)
call ... NativeLibraries.Load();
System.IO.FileNotFoundException: 'Could not load the library 'libeay32' at 'C:\...\win7-x86\libeay32.dll', because the file does not exist'

PS: win7-x64 is OK.

**Comment by qmfrederik** [comment]
Hi @rackliu,

This should have been fixed in [1.2.1-r195](https://www.nuget.org/packages/imobiledevice-net/1.2.1-r195).

If this issue persists, let me
