### ISSUE TITLE
Struggling to upload an Image to my iOS mobile device

### ISSUE THREAD

**Issue by iDanielD** [libimobiledevice-win32/imobiledevice-net#166]
Hey, 

I am having trouble uploading pictures from my computer to my iOS mobile device. 
So far I have tried to use the method "IMobileImageMounterApi.mobile_image_mounter_upload_image", but I have no idea what to use as a parameter. Below I have my code.
Could someone help me with this?

```
private void UploadImage(Image image)
{
            PlistHandle plistHandle = null;

            var imageMounter = LibiMobileDevice.Instance.MobileImageMounter;
            var byteArray = ImageToByteArray(image); // Returns a byte array from the selected image from my Computer.

            imageMounter.mobile_image_mounter_start_service(DeviceHandle, out var mobileImageMounterClientHandle, null);
            imageMounter.mobile_image_mounter_upload_image(mobileImageMounterClientHandle, "jpg", (uint)byteArray.Length, 
            null, 0, null, ??);
}
```

Thank you in advance!

**Comment by qmfrederik** [comment]
@iDanielD `mobile_image_mounter` is used to upload developer disk images (i.e. file archives), not pictures.

You can probably use AFC (the Apple File Conduit) to transfer files to/from your phone. Haven't done it myself, though.

**Comment by iDanielD** [comment]
@qmfrederik Thank you for your quick response. I just tried using the AFC, but I cant see there an option to upload an image. 
I have updated my Code to something like this:

```
private void UploadImage(Image image)
        {
            var afcApi = LibiMobileDevice.Instance.Afc;

            var byteArray = ImageToByteArray(image); // Returns a byte array from the selected image from my Computer.
            
            afcApi.afc_client_start_service(DeviceHandle, out var afcClientHandle, null).ThrowOnError();

            afcApi.??
        }

```
I linked all possbile afc methods below.
![image](https://user-images.githubusercontent.com/63862481/95432228-ab3e0680-094e-11eb-9e66-ed7e1129374c.png)
![image](https://user-images.githubusercontent.com/63862481/95432252-b6913200-094e-11eb-9b1c-405ad12d7084.png)
![image](https://user-images.githubusercontent.com/63862481/95432294-c3158a80-094e-11eb-95c4-779edb6d7abb.png)

**Comment by qmfrederik** [comment]
@iDanielD AFC allows you to open a file (afc_file_open) and then write to that file (afc_file_write). That's how you would upload a file. It's very similar to the file APIs in C (fopen, fwrite, fread,...)

You'd need to figure out in which directory you need to save the images.

**Comment by iDanielD** [comment]
@qmfrederik Alright I will test it myself and write back if I got any results. Thank you.

**Comment by iDanielD** [comment]
@qmfrederik I cannot get it to run. I don't understand how I should upload such a picture, if I open an already existing file from my cell phone and then write new information into it?
Will the picture not be overwritten then?

**Comment by qmfrederik** [comment]
If you specify a path to a file which does not exit, `afc_file_open` should create a _new_ file on the device.

**Comment by iDanielD** [comment]
Well, I see the problem. The file is being written, but I can't see it on my phone. I thought that if I write "**@"/DCIM/101APPLE "**" in the path, it will be displayed in this folder so I can view it in windows. But this is not the case. 
Is there maybe a common path for the albums on my iPhone where I can store my file and see it?

**Comment by qmfrederik** [comment]
You should be able to use `afc_read_directory` to get a listing of the directory contents, and get an idea of the directory structure (and know to which folder you can upload your picture).

Also make sure to properly close the file handle with afc_file_close, etc... .

**Comment by iDanielD** [comment]
@qmfrederik Ok after several attempts to find the right path, I decided to create a new album and save the pictures in it.
Do you perhaps know a way to create a new album on the device where I could save my pictures?

**Comment by iDanielD** [comment]
Has anyone found a solution?
