### ISSUE TITLE
Unable to load DLL 'libimobiledevice': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

### ISSUE THREAD

**Issue by gorilla227** [libimobiledevice-win32/imobiledevice-net#17]
Same issue as https://github.com/libimobiledevice-win32/imobiledevice-net/issues/14.
Open the new one for tracking because the original one was closed without solution.
I also tried to add runtime.win-x64.iMobileDevice-net & runtime.win-x86.iMobileDevice-net to my project via NuGet. However, I got the same exception.

**Comment by gorilla227** [comment]
I found that if I copied all files in bin\Debug\win7-x64\native  to bin\Debug then the exception will not be thrown.

**Comment by qmfrederik** [comment]
Ok, that makes sense. Probably the copy operation in one of the .targets files is off.

**Comment by qmfrederik** [comment]
Can you try to run

```
NativeLibraries.Load();
```

before using the libimobiledevice-net API and let me know if that fixes it?

**Comment by gorilla227** [comment]
No, I still have to manually copy files to avoid this exception.

**Comment by qmfrederik** [comment]
@gorilla227 I had a look at your project. You were using the latest released (and not prerelease) version. I've sent you a PR to update to the latest prerelease version. Your project works for me with the PR applied.

**Comment by gorilla227** [comment]
Confirmed the pre-release version works on my project.
Thanks a lot.

**Comment by NehaBector** [comment]
I have used the updated code gorilla227/iOS_Pilot with Update to imobiledevice-net 1.2.1-r196..but its giving me no device  

![No_Device](https://user-images.githubusercontent.com/49264675/55874242-6e555000-5baf-11e9-93ee-3bb86ed08cbf.png)
