### ISSUE TITLE
How to pair idevice using pair record plist?

### ISSUE THREAD

**Issue by pappanunny** [libimobiledevice-win32/imobiledevice-net#171]
Im looking for a way to use a pair record plist (already paired and in the Lockdown folder) to pair the idevice on a different host machine. I would like to bypass the trust dialogue and then pair it so that more information can be taken from the idevice. 

I used the pair record plist and then used the lockdownd_send(client, plist) to send pairing request (with "pair" as request)to the idevice. But is receiving "passwordprotected" as response from device and there is the trust alert on the idevice.

How can i move further to implement this?

**Comment by qmfrederik** [comment]
It should work if you just copy the pair record plist from the lockdown folder on your original host to your new host before you connect the device to your new host.
