### ISSUE TITLE
Xamarin Forms support

### ISSUE THREAD

**Issue by onurhazar** [libimobiledevice-win32/imobiledevice-net#172]
Hello, Is there any chance that we can use this api in a xamarin forms project? do you have any sample/demo project if supported? Thanks for the great tool. Appreciated.

**Comment by siddhijk** [comment]
Hi,  please provide xamarin implementation with "imobiledevice-net" , if possible please share sample project for communicating ios devices using usb in xamarin.

**Comment by qmfrederik** [comment]
I know virtually nothing about Xamarin Forms, and there are no plans to add Xamarin support to this repository, sorry.
