### ISSUE TITLE
'An Lockdown error occurred. The error code was SslError'

### ISSUE THREAD

**Issue by wickedlizerd** [libimobiledevice-win32/imobiledevice-net#18]
When attempting to run the code below, it throws an exception saying 'An Lockdown error occurred. The error code was SslError'.

Code:` lockdown.lockdownd_client_new_with_handshake(deviceHandle, out lockdownHandle, "Quamotion").ThrowOnError();`

Can't find a fix for this.

**Comment by qmfrederik** [comment]
Which version of iOS are you using? On what OS are you running this, and which .NET version?

**Comment by gorilla227** [comment]
I have the same issue.
iOS 10.3.3
OS: Windows 10
Target Framework: .Net 4.5.2

**Comment by wickedlizerd** [comment]
iOS 10.3.1
OS: Windows 10
Target Framework: 4.7

**Comment by qmfrederik** [comment]
I just tried with iOS 10.3.2, Windows 10 and .NET 4.6.1, and it works for me.

Can you make sure you run `NativeLibraries.Load();` at the beginning of your program? If possible, can you share your program?

Thanks!

**Comment by wickedlizerd** [comment]
I have tried that, however it throws an exception "System.ArgumentException: 'The path is not of a legal form."

**Comment by vladkorotnev** [comment]
.net 4.0, iOS 10.1.1, same thing for me. `NativeLibraries.Load();` is being run just before the `Application.Run(Form1);` line.

Possibly the binaries need to be updated to the git upstream version? 
Does anybody know how to build those on Windows in VS2010?

**Comment by qmfrederik** [comment]
@vladkorotnev The binaries are built on Windows using this project: https://github.com/libimobiledevice-win32/libimobiledevice

**Comment by vladkorotnev** [comment]
@qmfrederik Was it already updated for iOS 10-11 support which was included in the main repo of libimobiledevice recently? Are there any binaries available?

**Comment by qmfrederik** [comment]
@vladkorotnev Yes, it's updated - you can see it in the GitHub page: "This branch is 60 commits ahead of libimobiledevice:master.". Yes, there are binaries, there's a link to an AppVeyor CI build at the top of the readme. If you follow that link, you'll see the build artifacts which are the binaries.

**Comment by vladkorotnev** [comment]
@qmfrederik Thanks, replacing the binaries with ones from AppVeyor has fixed it! Seems like the NuGet package isn't being updated on time...
