### ISSUE TITLE
where do I find apple application support

### ISSUE THREAD

**Issue by SarKaa** [libimobiledevice-win32/imobiledevice-net#180]
So I saw that this needs usbmuxd, or apple application support for windows. I want to use this without installing itunes. In the itunes setup exe, I found a .msi installer called apple mobile device support 64. Is that the same one, because I seem to not have one called apple application support.  

In short, is apple mobile device support the same thing as apple application support, just updated?

Thank you

**Comment by qmfrederik** [comment]
Yes, Apple Mobile Device Support 64 is what you need.

**Comment by SarKaa** [comment]
thanks
