### ISSUE TITLE
Cannot find device

### ISSUE THREAD

**Issue by Visutronik** [libimobiledevice-win32/imobiledevice-net#181]
Hello,

i use the code from the main page.
But it doesn't found my devices. I tried an iPhone 8+ (iOS 14) and an iPad 4 (iOS 10).

I can see the device on my windows pc and i can access the storage from the device.
I use Visual Studio 2019 (Version 16.7.6).

Am I missing some kind of parameters or other kind of configurations?
Thanks in advance.

Best regards
Christian

**Comment by Maciejszuchta** [comment]
@Visutronik I had to install itunes on my Windows to let it detect IOS device.
https://support.apple.com/downloads/itunes

**Comment by Visutronik** [comment]
@Maciejszuchta Thank you very much. It works with itunes.
@qmfrederik Could you please write a requirement "itunes needed" onto your main page?
