### ISSUE TITLE
idevice pair not creating proper pair record plist in lockdown folder

### ISSUE THREAD

**Issue by Dantee296** [libimobiledevice-win32/imobiledevice-net#186]
iTunes mobiledevice creating 10kb plist for pair record
libimobildevice creating 7kb plist for pair record and it does that exacly when i call "idevicepair pair"

so even if device paired via idevicepair mobiledevice library wont accept plist created by idevicepair and have user trust device again.

using openssl 1.1.1.9 latest libimobiledevice

@qmfrederik  please let me know what could be the issue , Files Attached

[67d345af353eb431e4e9fe846b2233b2972e189b - mobiledevice.txt](https://github.com/libimobiledevice-win32/imobiledevice-net/files/6389514/67d345af353eb431e4e9fe846b2233b2972e189b.-.mobiledevice.txt)

[67d345af353eb431e4e9fe846b2233b2972e189b - idevicepair.txt](https://github.com/libimobiledevice-win32/imobiledevice-net/files/6389513/67d345af353eb431e4e9fe846b2233b2972e189b.-.idevicepair.txt)

**Comment by qmfrederik** [comment]
The difference between both pair records is that one is in the binary property list format, and the other in the XML property list format.  You should be able to use plutil to convert between both formats.

**Comment by Dantee296** [comment]
@qmfrederik how to ensure idevicepair generate xml property list ?

**Comment by qmfrederik** [comment]
`idevicepair` will call `lockdownd_pair`, which will save the pair record in `userpref_save_pair_record`. It [looks like that method](https://github.com/libimobiledevice/libimobiledevice/blob/25059d4c7d75e03aab516af2929d7c6e6d4c17de/common/userpref.c#L283-L295) is calling `plist_to_bin` instead of `plist_to_xml`.

So you can try changing that.

**Comment by Dantee296** [comment]
@qmfrederik thanks now both files are 10kb 
but mobiledevicedll based code still not accepting it

and by comparing it figured keys missing

"EscrowBag", "HostID" , "HostPrivatekey"

**Comment by Dantee296** [comment]
openssl version issue 
had to update to latest version
