### ISSUE TITLE
How can I get success on mobilebackup2 version exchange?

### ISSUE THREAD

**Issue by 18photos** [libimobiledevice-win32/imobiledevice-net#19]
This is my code for backup iPhone 5C device to my PC...
But I'm trying to  'mobilebackup2_version_exchange', thrown 'error code -6 : NOCOMMONVERSION'

How can I solve this problem?

Try

            Dim _UDIDs As ReadOnlyCollection(Of String) = Nothing
            Dim _COUNT As Integer = 0

            _WriteLog("idevice_get_device_list", idevice_get_device_list(_UDIDs, _COUNT).ToString())

            For Each _UDID In _UDIDs

                Dim _iDeviceHandle As iDeviceHandle = iDeviceHandle.Zero
                _WriteLog("idevice_new", idevice_new(_iDeviceHandle, _UDID).ToString)

                Dim _LockdownClientHandle As LockdownClientHandle = LockdownClientHandle.Zero
                Dim _LockdownServiceDescriptorHandle As LockdownServiceDescriptorHandle = LockdownServiceDescriptorHandle.Zero
                _WriteLog("lockdownd_client_new_with_handshake", lockdownd_client_new_with_handshake(_iDeviceHandle, _LockdownClientHandle, "iDevice").ToString)
                _WriteLog("lockdownd_start_service-AFC", lockdownd_start_service(_LockdownClientHandle, "com.apple.afc", _LockdownServiceDescriptorHandle).ToString)

                Dim _AfcClientHandle As AfcClientHandle = AfcClientHandle.Zero
                _WriteLog("afc_client_new", afc_client_new(_iDeviceHandle, _LockdownServiceDescriptorHandle, _AfcClientHandle).ToString)

                Dim _MobileBackup2ClientHandle As MobileBackup2ClientHandle = MobileBackup2ClientHandle.Zero
                _WriteLog("lockdownd_start_service-MB2", lockdownd_start_service(_LockdownClientHandle, "com.apple.mobilebackup2", _LockdownServiceDescriptorHandle).ToString)
                '_WriteLog("lockdownd_start_service-MB2", lockdownd_start_service_with_escrow_bag(_LockdownClientHandle, "com.apple.mobilebackup2", _LockdownServiceDescriptorHandle).ToString)
                _WriteLog("mobilebackup2_client_new", mobilebackup2_client_new(_iDeviceHandle, _LockdownServiceDescriptorHandle, _MobileBackup2ClientHandle).ToString)

                '/* send Hello message */
                'Dim _Local_Version_Array As Double() = New Double() {2.0, 2.1}
                'Dim _Local_Version As IntPtr = Marshal.AllocCoTaskMem(8 * _Local_Version_Array.Length)
                'Marshal.Copy(_Local_Version_Array, 0, _Local_Version, _Local_Version_Array.Length)

                Dim _Local_Version_Array As Double() = New Double() {2.0, 2.1}
                Dim _Local_Version As IntPtr = Marshal.AllocCoTaskMem(8 * _Local_Version_Array.Length)
                Marshal.Copy(_Local_Version_Array, 0, _Local_Version, _Local_Version_Array.Length)

                Dim _Remote_Version As Double = 0.0
                _WriteLog("mobilebackup2_version_exchange", mobilebackup2_version_exchange(_MobileBackup2ClientHandle, _Local_Version, 2, _Remote_Version).ToString)

                '_iDeviceHandle.Dispose()
                '_LockdownClientHandle.Dispose()

                ListBox1.Items.Add("=====================================================================")

            Next

        Catch ex As Exception

            MsgBox(ex.ToString)

        End Try

**Comment by qmfrederik** [comment]
This should be fixed in [version 1.2.1-r196](https://www.nuget.org/packages/imobiledevice-net/1.2.1-r196), can you download that version and see if it works for you?

**Comment by 18photos** [comment]
It's OK.
Very nice result.
Thank you:)

**Comment by qmfrederik** [comment]
Thanks for the update! Since it seems to work, I'll go ahead and close this issue.
