### ISSUE TITLE
How can I check null of plisthandle?

### ISSUE THREAD

**Issue by 18photos** [libimobiledevice-win32/imobiledevice-net#20]
This is C++ code and my VB.NET code.
They are use "while (NULL == switch_node". But I'm only use vb.net.

How can I check plisthandle is null?

Thank you.

contact_node = plist_array_get_item(array, 0);
	switch_node = plist_array_get_item(array, 0);

	while (NULL == switch_node
	    && check_string(contact_node, "com.apple.Contacts")
	    && check_string(switch_node, "SDMessageDeviceReadyToReceiveChanges")) {

		plist_free(array);
		array = NULL;

		array = plist_new_array();
		plist_array_append_item(array, plist_new_string("SDMessageAcknowledgeChangesFromDevice"));
		plist_array_append_item(array, plist_new_string("com.apple.Contacts"));

		ret = mobilesync_send(client, array);
		plist_free(array);
		array = NULL;

		ret = mobilesync_receive(client, &array);

		contact_node = plist_array_get_item(array, 0);
		switch_node = plist_array_get_item(array, 0);
	}

Dim _Contact_Node As PlistHandle = PlistHandle.Zero
        Dim _Switch_Node As PlistHandle = PlistHandle.Zero

        While _Switch_Node Is Nothing And _Check_String(_Contact_Node, "com.apple.Contacts") And _Check_String(_Switch_Node, "SDMessageDeviceReadyToReceiveChanges")

            _PlistHandle = Nothing
            _PlistHandle = plist_new_array()

            plist_array_append_item(_PlistHandle, plist_new_string("SDMessageAcknowledgeChangesFromDevice"))
            plist_array_append_item(_PlistHandle, plist_new_string("com.apple.Contacts"))

            _Ret = mobilesync_send(_MobileSyncClientHandle, _PlistHandle)
            _PlistHandle = Nothing

            _Ret = mobilesync_receive(_MobileSyncClientHandle, _PlistHandle)

            _Contact_Node = plist_array_get_item(_PlistHandle, 0)
            _Switch_Node = plist_array_get_item(_PlistHandle, 0)

        End While

**Comment by qmfrederik** [comment]
A null pointer in unmanaged code will surface as `IntPtr.Zero` in managed code.
In your scenario, if `switch_node` is a `PlistHandle`, check for `PlistHandle.Zero`.
