### ISSUE TITLE
NuGet package not working with .NET Framework greater than 4.0

### ISSUE THREAD

**Issue by stefanodriussi** [libimobiledevice-win32/imobiledevice-net#24]
I've tried to add a reference to the imobiledevice-net package on NuGet but if I target .NET Framework v 4.5 i get a runtime error telling me it can't load the dependent dlls.
Retargeting the same project to target .NET Framework 4.0 works. 
Could you please add support for newer framework versions too ?

**Comment by qmfrederik** [comment]
Can you provide a bit more of information on which error you got? We've been using imobiledevice-net on .NET 4.6.2 for quite a while without issues.

**Comment by stefanodriussi** [comment]
Ok this really strange.
After reading your response i jumped back to my little project solution and tried to retarget first to 4.5 then 4.6 and surprisingly it worked.
Created three new projects from scratch 4.0 4.5 4.6 and added imobiledevice-net package from nuget to the three of them. Run them and got the runtime exception on all three
```
System.DllNotFoundException: 'Unable to load the DLL 'libimobiledevice': Unable to find specified module. (Exception from HRESULT: 0x8007007E).'
```
The code i'm using is this
```
NativeLibraries.Load();
deviceApi = new iDeviceApi(LibiMobileDevice.Instance);
deviceApi.idevice_event_subscribe((ref iDeviceEvent devEvent, IntPtr data) =>
{
    switch (devEvent.@event)
    {
       // switch code here ...
    }
}
```
the exception shows up as soon as i call `idevice_event_subscribe` method

**Comment by qmfrederik** [comment]
It looks like it's loading the 64-bit imobiledevice.dll on 32-bit .NET or the other way around.
Can you change your project to target x64 or x86 instead of Any CPU?

**Comment by stefanodriussi** [comment]
After some tests, including changing the target to x64, what I discovered is that if I manually copy all the contents from the `win7-x64\native` folder directly inside my `bin/Debug one` , it works but for instance, if only copy that `libimobiledevice.dll` it keeps crashing when i launch it.

**Comment by qmfrederik** [comment]
@stefanodriussi Yes, you need all files from the `win7-x64\native` folder for it to work. `libimobiledevice.dll` depends on some other `.dll` files, so that's why you get that behavior.

Out of interest, which version of the NuGet package are you using?

**Comment by stefanodriussi** [comment]
@qmfrederik sorry for the late response.
I'm using NuGet package version 1.2.0.112

**Comment by stefanodriussi** [comment]
I've noticed a strange behavior:
if I copy all the assemblies (from the correct architecture folder) inside my application root folder, everything works but if i delete the original native folder it throws an [exception
](https://github.com/libimobiledevice-win32/imobiledevice-net/blob/ce0aba9221e53b2b5c0f38778d8959b88c81b9af/iMobileDevice-net/NativeLibraries.cs#L90) .
If I delete everything from that folder and leave it empty, apparently the previous check goes through and it loads the libraries.
