### ISSUE TITLE
Remove .exe from native payload

### ISSUE THREAD

**Issue by deakjahn** [libimobiledevice-win32/imobiledevice-net#27]
I can't really see a reason why all the sample EXE files are packaged into the package native folder and get automatically deployed together with the required DLLs. If I build a .NET program to use the DLLs as a bridge to the iOS device, I have my own code naturally and I don't need the samples to operate. Could those be removed from the package?

**Comment by qmfrederik** [comment]
For most of the executables, that holds true. For `iproxy`, and `usbmuxd`, there may be some scenarios where your application may want to launch them. For example, `iproxy` gives you an easy way to set up an out-of-process TCP proxy to a socket on your device. I also use `idevice_id` and `idevicesyslog` from time to time for troubleshooting purposes.

I'd be happy to accept a PR that moves the utilities out of the NuGet package (with the exception of the tools mentioned before); the only requirement I'd put forward is that the build then produces a `.zip` file which includes the native libraries and utilities. Quite some people seem to rely on the command-line utilities we provide as part of the project and this should be an easy way to help them.

**Comment by qmfrederik** [comment]
Sorry to disturb you - I'm doing a cleanup of old issues. We currently don't mind having the utilities included in the NuGet package so it's not something we will change on our own. But I'd be happy to review a PR if it comes to that 😄 .
