### ISSUE TITLE
Crash on device unplug with pending read

### ISSUE THREAD

**Issue by stefanodriussi** [libimobiledevice-win32/imobiledevice-net#31]
I have a problem when I physically disconnect the cable from the connected device and I have a pending call to `idevice_connection_receive_timeout `
Even if I wrap the call in a try catch block, the application stops working. If i try to debug with VS, shows only `Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine (e.g. only native runtime code is executing).` and if I hit continue, it stops the debug session and kills the app.
I also noticed that this happens before even receiving the device disconnect message on the `idevice_event_subscribe` handles.
Is there a way to suppress this behavior ? All I want to do is just acknowledge the cable was unplugged while waiting for data and keep going on.

**Comment by qmfrederik** [comment]
We'll first need to find out which piece of the native code is crashing. You can either share a very simple repro, or do the following:
- On your PC, clone and compile https://github.com/libimobiledevice-win32/libimobiledevice in Debug mode
- Copy the output (imobiledevice.dll + imobiledevice.pdb) to `.nuget\packages\imobiledevice-net\1.2.1-r212\runtimes\win7-x64\native` or your app output directory
- Repro the behavior, and when asked to debug your application when it crash, make sure to debug using a C++ debugger and load the symbols from your `imobiledevice.pdb` symbols file.

This should get you the native stack trace and a better idea of what failed and why.

**Comment by stefanodriussi** [comment]
A little late but finally I've found the time to dig deeper into this and it turned out it was not related to a pending read as I initially thought but rather to GC issue as described here #25 
In particular, my code was this
```
LibiMobileDevice.Instance.iDevice.idevice_event_subscribe((ref iDeviceEvent devEvent, IntPtr data) =>
{
    switch (devEvent.@event)
    {
        // code here ...
     }
}, new IntPtr());
```
I've declared a private variable holding a reference to that delegate and now it works properly.

**Comment by qmfrederik** [comment]
Cool, thanks for sharing!
