### ISSUE TITLE
Dll fails to load if dependent project uses nuget package

### ISSUE THREAD

**Issue by igor84** [libimobiledevice-win32/imobiledevice-net#32]
I have a solution with two project: MainProj and CoreProj. MainProj depends on CoreProj and CoreProj uses imobiledevice nuget package. When I run this I get this error:

The directory 'C:\\MySolution\\MainProj\\bin\\Debug' does not contain a subdirectory for the current architecture. The directory 'C:\\MySolution\\MainProj\\bin\\Debug\\win7-x64' does not exist.

When I check I see that it really doesn't have that folder there. I see that this folder exists under C:\\MySolution\\**CoreProj**\\bin\\Debug\\. So it got copied under the CoreProj but not under the MainProj. Looking online the best I could find is this: 

https://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory

But after trying to change the targets file I still didn't manage to get those folders to appear in the MainProj.

I am using VisualStudio 2017 on Window 10.

**Comment by egfconnor** [comment]
I am having this issue too.

**Comment by qmfrederik** [comment]
Yes, that's unfortunately a limitation of how NuGet packages work in the "classic" .NET projects.

There's two things you can try:
- Add a reference to imobiledevice-net in your `MainProj`.
- Use the .NET Core 2.0 SDK to build your project. This handles all NuGet packages transitively. You can still target the traditional .NET Framework.

Let me know if either of the two options work.

**Comment by igor84** [comment]
I updated Visual Studio, installed .NET Core 2.0.3 but I couldn't find any option in project settings to select Core 2 and it is still building the same. I guess I can also add a a Post-Build event to copy these folders to proper bin directory.

**Comment by qmfrederik** [comment]
@igor84 I'm doing a cleanup of open issues and this is a pretty old issue :).

If you want to target .NET Core 2.0, I think you'll need to create a new .csproj file which targets .NET Core and then add your .cs & other files to that project.

That said, the status still is:
- If you're using the "new" csproj file format (i.e. use the .NET Core SDK to build your project and target .NET Core or .NET Desktop), the native libraries will be found if you reference imobiledevice-net directly or indirectly
- If you're using the "old" csproj file format (e.g. created with VS2012), you will need to either at a reference to imobiledevice-net to your "top level" projects (e.g. the project that is being executed), or use a post-build event/... to copy the files yourself.

If you have further questions, happy to help, but closing the issue for now.
