### ISSUE TITLE
How to reboot a device

### ISSUE THREAD

**Issue by ollesegergren** [libimobiledevice-win32/imobiledevice-net#33]
Hi, how do I reboot/respring the device? Can you someone please show me an example?

**Comment by qmfrederik** [comment]
You can use the `DiagnosticsRelay.diagnostics_relay_restart` method. It takes an `DiagnosticsRelayClientHandle` which represents the diagnostics service running on the device.
To get such a handle, you first need to have a iDeviceHandle which you use to identify your device, so you'd need to so something like this, where `udid` is the UDID of your device:

(pseudo-code from the top of my head, you'd also need to clean up all your handles after this)

```csharp
var idevice = LibiMobileDevice.Instance.iDevice;
var diagnostics = LibiMobileDevice.Instance.DiagnosticsRelay;

// Get a handle to the device
iDeviceHandle deviceHandle;
idevice.idevice_new(out deviceHandle, udid).ThrowOnError();

// Get a handle to the diagnostics service running on the device
DiagnosticsRelayClientHandle  diagnosticsHandle;
diagnostics.diagnostics_relay_client_start_service(deviceHandle, out diagnosticsHandle, null).ThrowOnError();

diagnostics.diagnostics_relay_restart(diagnosticsHandle, DiagnosticsRelayAction.ActionFlagWaitForDisconnect ).ThrowOnError();
```

**Comment by qmfrederik** [comment]
I'm going to close this issue as I believe I've answered your question, let me know should this not be the case.
