### ISSUE TITLE
Distinguish between USB and WiFi (or just ignore the latter)

### ISSUE THREAD

**Issue by stefanodriussi** [libimobiledevice-win32/imobiledevice-net#34]
Hi,
I'm here again asking for your support. 
I have a problem with Apple "Sync over WiFi" feature because when I receive the notification of a newly connected device, I have no way to determine if it's a USB connection or one over WiFi.
According to libimobiledevice [repo ](https://github.com/libimobiledevice/libimobiledevice/issues/152)they still need to implement some kind of switch or flag to solve this. 
In the mean time, I've found [this ](https://github.com/ericcastro/libusbmuxd/blob/6e2b08865be606387e12a05b7aee6e4db5afcf08/src/libusbmuxd.c#L904) repo where the guy just drops every notification that he identifies as WiFi (by ... looking at that product_id property). I've been trying rebuild all the components from source applying that change but so far I had no luck: WiFi sync keeps triggering those notification.
Would it be possible to handle this scenario in some way ? All I really need is to ignore those WiFi connections.
Thanks

**Comment by qmfrederik** [comment]
Which operating system are you using?

**Comment by stefanodriussi** [comment]
I'm using Windows 10 Professional on my development machine and the same
happens on a Windows 8 VM running on a MacBook Pro with MacOS Sierra.

Il 26 nov 2017 22:16, "Frederik Carlier" <notifications@github.com> ha
scritto:

**Comment by stefanodriussi** [comment]
I've found a quick workaround for the moment: checking the `product_id` property as suggested on the aforementioned repository. Luckily that field is set to 0 for WiFi connection and to a positive value for USB ones. Now, whenever I receive a message on the subscription handler, I read the corresponding device info
```
var iDeviceApi = new iDeviceApi(LibiMobileDevice.Instance);
var info = new iMobileDevice.Usbmuxd.UsbmuxdDeviceInfo();
LibiMobileDevice.Instance.Usbmuxd.usbmuxd_get_device_by_udid(devEvent.udidString, ref info);
```
and then I can check the `product_id` field

**Comment by qmfrederik** [comment]
@stefanodriussi I'm cleaning up some old issues; it looks like you've been able to to differentiate between WiFi and USB connections so this issue can be closed. Feel free to comment if otherwise.

**Comment by felyppers** [comment]
Hey guys, I had this same issue this week and solved by disabling the wifi service in the MAC.

In your MAC, use the command below to list your network services
networksetup -listallnetworkservices

Write down the service name similar to iPhone USB and run:
networksetup -setnetworkserviceenabled SERVICE_NAME off

After that, restart your mobile and it should work, but I agree that should be a flag to ignore Wi-Fi connections, similar to "ios-deploy --no-wifi" flag.
