### ISSUE TITLE
How can I get all of Contacts in iPhone?

### ISSUE THREAD

**Issue by 18photos** [libimobiledevice-win32/imobiledevice-net#39]
I was read all web documents...
But it was not working.

Mobilesync -> usbmux error..
MobileBackup2 -> not working...

Can I read my iPhone's addressbook?

**Comment by qmfrederik** [comment]
We try to keep the issues in this repository limited to the core of the imobiledevice-net project, which is to provide a .NET wrapper around libimobiledevice (and builds of libimobiledevice for Windows, Linux and macOS).

We don't really provide support on how to use libimobiledevice to achieve a specific task, that would be up to you.

I would recommend you ask this question on StackOverflow or a similar site. Alternatively, we can provide consulting around imobiledevice-net on a commercial basis.
