### ISSUE TITLE
Read and Write on .Libray dictonary.

### ISSUE THREAD

**Issue by MoonTechnolabs** [libimobiledevice-win32/imobiledevice-net#47]
We able to perform read and write on Document folder but we getting **permission denied** error when we try to write or create a file in Library dictionary.

we using  **VendDocuments** for house arrest commnad
houseassest.house_arrest_send_command(house_client, "VendDocuments", appId);

**Comment by qmfrederik** [comment]
I think this is a limitation of the iOS security model, and I think you can only access documents for applications that are built with the `get-task-allow` entitlement set to true.

That said, we try to keep the issues in this repository limited to the core of the imobiledevice-net project, which is to provide a .NET wrapper around libimobiledevice (and builds of libimobiledevice for Windows, Linux and macOS).

We don't really provide support on how to use libimobiledevice to achieve a specific task, that would be up to you.

I would recommend you ask this question on StackOverflow or a similar site. Alternatively, we can provide consulting around imobiledevice-net on a commercial basis.
