### ISSUE TITLE
get: System.ComponentModel.Win32Exception: 'Could not load the library 'libiconv' at 'project_name\bin\x64\Debug\win7-x64\libiconv.dll'. The error code was 126'

### ISSUE THREAD

**Issue by DavidBates** [libimobiledevice-win32/imobiledevice-net#54]
As soon as it hits NativeLibraries.Load(); I get this error 
Tried retargeting to .net 4.5 to no avail. 
running 1.2.1-r388
![image](https://user-images.githubusercontent.com/1494603/42399210-f02bf2aa-813a-11e8-82bf-a89969d62c91.png)

**Comment by Hareis** [comment]
我看了源码 在vsdebug编译后的文件夹 新增了 native 文件夹 建议复制所有生成的二进制文件到debug目录下
![image](https://user-images.githubusercontent.com/11290701/43044983-89597566-8de2-11e8-93a8-1c36b5543b14.png)

**Comment by lief480** [comment]
I am getting this same issue on prerelease version 1.2.1-r388

**Comment by qmfrederik** [comment]
I believe this is fixed in version 1.2.31. Can you give that version a try, and reopen the issue (or open a new one) if this issue persist?

Thanks!
