### ISSUE TITLE
PlistError

### ISSUE THREAD

**Issue by kalehv** [libimobiledevice-win32/imobiledevice-net#55]
I am using the code snippet provided that gives the list of devices connected.
It is throwing error at the line 
``` C#
lockdown.lockdownd_client_new_with_handshake(deviceHandle, out lockdownHandle, "Quamotion").ThrowOnError();
```
Error is - An Lockdown error occurred, the error code was PlistError.

I am using iPhone 8 with iOS 11.4.1

**Comment by qmfrederik** [comment]
Are you on the latest version (1.2.1-r388)?

**Comment by qmfrederik** [comment]
@kalehv  I'm closing this issue because I haven't heard back from you; feel free to open if you have more information.

**Comment by yogendra123456** [comment]
hi @kalehv qmfrederik i am using imobiledevice-net on windows system that shows the list of device...
but after that it give an error on handshake function....

lockdown.lockdownd_client_new_with_handshake(deviceHandle, out lockdownHandle, "Quamotion").ThrowOnError();

Error is - An Lockdown error occurred, the error code was PlistError.

i am using latest version 1.2.204

My device is iPhone 5s, IOS 12.4.7

thanks in advanced..
