### ISSUE TITLE
win10 loaded libimobiledevice.dll file 

### ISSUE THREAD

**Issue by Hareis** [libimobiledevice-win32/imobiledevice-net#56]
我在win10 x64位的系统中编写了代码
全部正确加载dll文件后，能获取udid
但是在与手机握手的时候发生了SSL错误
![image](https://user-images.githubusercontent.com/11290701/43045018-3699e3be-8de3-11e8-8c07-967d7b0f3993.png)

换作其他版本 的时候就能正常获取手机信息
现在怀疑打包文件中缺少了SSL文件 

希望能帮忙解答下，我该怎么办

**Comment by qmfrederik** [comment]
I'm sorry, this repository only accepts issues in English.
