### ISSUE TITLE
XML comment has badly formed XML

### ISSUE THREAD

**Issue by ajdude** [libimobiledevice-win32/imobiledevice-net#76]
Add missing equals sign between `cref` and `\`.

File: iMobileDevice.Generator/ApiExtractor.cs

Code: `constructor.Comments.Add(new CodeCommentStatement($"Initializes a new instance of the <see cref\"{nativeClass.Name}\"/> class", true));`

**Comment by qmfrederik** [comment]
Thanks for catching this! Do you feel like creating a PR that fixes this?

**Comment by ajdude** [comment]
Resolved in PR #77
