### ISSUE TITLE
Disconnecting iOS device on Windows 10 issue

### ISSUE THREAD

**Issue by donaghy** [libimobiledevice-win32/imobiledevice-net#78]
I have a application build in c# running on Windows 10 (32bit or 64bit) that will detect and connect to an iOS device running iOS 11 without issue. There is application on the iOS device that will transfer data back and forth but if I pull the USB cable from the iOS device the iOS application will freeze and cease to respond.

The same behaviour does not occur on Windows 7 (32bit or 64bit) and we are able to handle the issue raised.

Is there a reason why this may be happening or known method to better handle this?

**Comment by doestmatter** [comment]
@donaghy Could you share or explain a little bit about the code in iOS to communicate with the app in Windows? Thanks in advance!

**Comment by donaghy** [comment]
I'm using xamarin to build the iOS app and have discovered that it's when the iOS is receiving content from the windows service that we only see this issue, not when sending data. I don't have the project code to hand at the moment but I'll post sample code when I do.

As a work around we've found the using Socket.ReceiveAsync with callback will work adequately. It does not crash the app but its also does not recognise a disconnect when the cable is detached. We can manage this with a timeout however.

**Comment by qmfrederik** [comment]
I'm going to go ahead & close this as it's not directly related to imobiledevice-net, and it looks like you've been able to fix the issue on your side.
