### ISSUE TITLE
Problem running on macOS

### ISSUE THREAD

**Issue by writzx** [libimobiledevice-win32/imobiledevice-net#80]
When trying to build on macOS, I am getting this error where the libraries cannot be loaded. I'm not sure what it means in this context. [I hope it doesn't need `libimobiledevice` to be installed to actually run?]

    System.DllNotFoundException: "Unable to load shared library 'imobiledevice' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libimobiledevice, 1): image not found"
      at iMobileDevice.iDevice.iDeviceNativeMethods.idevice_event_subscribe(iDeviceEventCallBack callback, IntPtr userData)\n   at iMobileDeviceTest.Program.Main(String[] args) in /Users/writwick/VSProjects/iMobileDeviceTest/Program.cs:14

I have tried using VSCode at first and moved to Visual Studio for mac later on to get the same error every time I tried to run.

This simple code in a new project reproduces this error:

    using System;
    using iMobileDevice;
    using iMobileDevice.iDevice;

    namespace iMobileDeviceTest {
        class Program {
            static void Main(string[] args) {
                Console.WriteLine("Hello World!");

                NativeLibraries.Load();

                LibiMobileDevice lib = new LibiMobileDevice();

                lib.iDevice.idevice_event_subscribe((ref iDeviceEvent er, IntPtr p) => { }, IntPtr.Zero);
            }
        }
    }

### **NOTE:**
If at all possible, I would like to use VSCode to build and run rather than Visual Studio.

### **UPDATE:**

Adding to the question, when I ran the program with environment variable `DYLD_PRINT_LIBRARIES=YES` (In Project Default Run Configuration), I got this output just before the error was hit.
```
dyld: loaded: /usr/lib/libxslt.1.dylib
dyld: loaded: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.1.5/libclrjit.dylib
dyld: loaded: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.1.5/System.Globalization.Native.dylib
dyld: loaded: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.1.5/System.Native.dylib
dyld: loaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libimobiledevice.dylib
dyld: loaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libssl.1.0.0.dylib
dyld: loaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libcrypto.1.0.0.dylib
dyld: loaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libusbmuxd.dylib
dyld: loaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libplist.dylib
dyld: unloaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libimobiledevice.dylib
dyld: unloaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libssl.1.0.0.dylib
dyld: unloaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libcrypto.1.0.0.dylib
dyld: unloaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libusbmuxd.dylib
dyld: unloaded: /Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/libplist.dylib
```
I proceeded to add a new variable `DYLD_FALLBACK_LIBRARY_PATH` to the environment variables, pointing to the path for the libraries where nuget unpacked them: `/Users/writwick/.nuget/packages/imobiledevice-net/1.2.67/runtimes/osx-x64/native/` (in my system).

The code runs perfectly now. Interestingly, all the `dyld: unloaded` lines disappeared.
(I'm not sure if its meant to be done this way).

My question would be how to handle this during deployment for a different system.

**Comment by qmfrederik** [comment]
That's odd. The problem (`DllNotFoundException`) combined with the workaround (`DYLD_FALLBACK_LIBRARY_PATH`) indicate that there is an issue loading one of the native libraries.

The CI build for imobiledevice-net includes a scenario very similar to yours, on macOS, and it is green.

I don't have a mac with me right now but I should be able to have a look at this early next week.

The real question probably is why these libraries are being unloaded. You can try to set `LD_DEBUG=libs` or `LD_DEBUG=all`, it should dump more information about what's going on.

**Comment by writzx** [comment]
As I noticed there was no publish option in the mac version of the visual studio, I used the windows version to get a standalone package. I could run the build on my mac using the usual `DYLD_FALLBACK_LIBRARY_PATH` set using terminal to the relative `./runtimes/osx-x64/native/`.

I also tried running with `LD_DEBUG=libs` and `LD_DEBUG=all` separately, but the output was exactly the same.

**Comment by writzx** [comment]
This still happens when I try to run a self-contained build on any other mac system. The build is done using:

```
dotnet publish <project.csproj> --self-contained -c Release -r osx-x64
```

And it fails with the same error message as above. Setting the `DYLD_PRINT_LIBRARIES=YES` prints the same old output where the libraries are first loaded and then unloaded. And also setting the `DYLD_FALLBACK_LIBRARY_PATH=.` perfectly loads the libraries and runs the program.

(As usual this doesn't happen in windows.)
