### ISSUE TITLE
System.DllNotFoundExeption: imobiledevice on mac

### ISSUE THREAD

**Issue by osmanraifgunes** [libimobiledevice-win32/imobiledevice-net#83]
### PROGRAM
Demo app in repo

### ERROR
`System.DllNotFoundException: imobiledevice`

### CONSOLE LOG

> dyld: loaded: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/4.5/mscorlib.dll.dylib
dyld: unloaded: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/4.5/mscorlib.dll.dylib
dyld: loaded: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/4.5/mscorlib.dll.dylib
dyld: unloaded: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/4.5/mscorlib.dll.dylib
Starting the imobiledevice-net demo
The application was terminated by a signal: SIGHUP
Unhandled Exception:
System.DllNotFoundException: imobiledevice
  at (wrapper managed-to-native) iMobileDevice.iDevice.iDeviceNativeMethods.idevice_get_device_list(intptr&,int&)
  at iMobileDevice.iDevice.iDeviceNativeMethods.idevice_get_device_list (System.Collections.ObjectModel.ReadOnlyCollection1[System.String]& devices, System.Int32& count) [0x0000d] in D:\a\1\s\imobiledevice-net\iDevice\iDeviceNativeMethods.Extensions.cs:34 
  at iMobileDevice.iDevice.iDeviceApi.idevice_get_device_list (System.Collections.ObjectModel.ReadOnlyCollection1[System.String]& devices, System.Int32& count) [0x00000] in D:\a\1\s\imobiledevice-net\iDevice\iDeviceApi.cs:126 
  at Robotic.LocalRecorder.Program.Main (System.String[] args)

I added `DYLD_PRINT_LIBRARIES=YES` line to env. variable. It gives info that loaded all libraries. However, i see the last 2 libraries have problem. And program gives error DLLNotFoundException on `var ret = idevice.idevice_get_device_list(out udids, ref count);` line of demo app.

**Comment by osmanraifgunes** [comment]
I realized that demo app works if sets as .net core. I want to use it in .Net 4.5 framework on mac. Is that possible ? Thanks

**Comment by qmfrederik** [comment]
It should be possible, but I don't use Mono on Mac (only .NET Core). To get this working, you'll need to make sure that the various `.dylib` files which live in `~/.nuget/packages/imobiledevice-net/1.2.71/runtimes/osx-x64/native/` are copied to the output folder of your project.

You can do this manually, or we can update the NuGet package with a `.targets` file which does this for you. We already do this on Windows (see e.g. [net45/iMobileDevice-net.targets](https://github.com/libimobiledevice-win32/imobiledevice-net/blob/master/iMobileDevice-net/build/net45/iMobileDevice-net.targets)).

Supporting Mono on Mac is not a goal for me, but I'd be happy to accept PRs which improve this scenario.

**Comment by osmanraifgunes** [comment]
I copied all dylib files under given directory, however still not working. I cannot understand whether problem is about library files or not.

**Comment by fluffyclaret** [comment]
@osmanraifgunes Did you get any further with this issue? I am experiencing the same error.

**Comment by osmanraifgunes** [comment]
Still getting same error. I tried the above solution but not working. Stil trying other options. @fluffyclaret

**Comment by osmanraifgunes** [comment]
mono Command line working. `<Exe path>: mono <name>.exe` working with dylib files copy solution. Hovewer, visual studio on mac not working when press the run.
