### ISSUE TITLE
 Update imobiledevice-net to imobiledevice-net 1.2.1-r196 and I also tried latest version of imobiledevice-net in windows..but its giving me no device

### ISSUE THREAD

**Issue by NehaBector** [libimobiledevice-win32/imobiledevice-net#86]
![No_Device](https://user-images.githubusercontent.com/49264675/55939903-98188080-5c5c-11e9-8cc0-3008e53da7fc.png)

**Comment by qmfrederik** [comment]
Please make sure:
- You installed iTunes on your PC
- You have trusted your PC on your device
- Your device is visible in iTunes
