### ISSUE TITLE
Getting Unknown error house_arrest_client_start_service

### ISSUE THREAD

**Issue by MoonTechnolabs** [libimobiledevice-win32/imobiledevice-net#87]
some time i getting **Unknown error** when calling **house_arrest_client_start_service**.
If you call multiple time then it throwing unknown error.
`house_arrest_client_start_service(iDeviceHandle device, out HouseArrestClientHandle client, string label);`

**Comment by qmfrederik** [comment]
Do you have sample code which shows how you're using imobiledevice-net and getting this issue? If so, please share & reopen.
