### ISSUE TITLE
Binaries not available

### ISSUE THREAD

**Issue by bluepuma77** [libimobiledevice-win32/imobiledevice-net#88]
The mentioned binary can not be found on AppVeyor.

Windows (x64) | libimobiledevice-1.2.1-win-x64.zip | AppVeyor

**Comment by qmfrederik** [comment]
We moved to Azure Pipelines. The latest binaries are at https://dev.azure.com/libimobiledevice-win32/imobiledevice-net/_build/results?buildId=419 . Click the blue Artifacts button in the upper right corner of the screen.
