### ISSUE TITLE
Backup and Restore in Libimobiledevice Library C#

### ISSUE THREAD

**Issue by NehaBector** [libimobiledevice-win32/imobiledevice-net#89]
Hi
I am stuck with libimobiledevice library in C#. I am using this code : https://github.com/libimobiledevice-win32/imobiledevice-net  and got success with the methods given. I am getting udids and device name as well but I want to take backup  and restore the mobile data. But I don't know which methods should be used for the same. Please guide me on this. And it would be very helpful if you provide working examples.

**Comment by qmfrederik** [comment]
@NehaBector If you want to do backup & restore in C#, you'll have to more or less port [idevicebackup2](https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicebackup2.c) to C#. All the methods which idevicebackup2 calls are exposed in the C# API, but porting can take some time.

Alternatively, you can also just call idevicebackup2.exe from your C# code. That may be an easier option.

**Comment by NehaBector** [comment]
Hi Frederik
Thanks for your reply. As porting was time consuming, I cloned https://github.com/libimobiledevice-win32/libimobiledevice. It is a c++ code and also has idevicebackup2. I resolved some errors in it like path errors of *.h files and now I am getting .obj file errors showing some methods missing/unresolved.
![ObjErrors](https://user-images.githubusercontent.com/49264675/58304697-fc5d6100-7e12-11e9-8c06-ddac55f594ea.PNG)

**Comment by qmfrederik** [comment]
@NehaBector It's probably easier if you just download a compiled copy of idevicebackup2. You can download it at https://dev.azure.com/libimobiledevice-win32/imobiledevice-net/_build/results?buildId=419 - then click the blue Artifacts link in the upper right corner, and select binaries.

**Comment by NehaBector** [comment]
@qmfrederik I decomplied idevicebackup2.exe. The decompiler gives the error: Not valid CLR asssembly.  Would you also tell me the parameters to pass when run exe to run the idevicebackup2.exe.

**Comment by qmfrederik** [comment]
`idevicebackup2.exe` is a console utility written in C, not C#. You won't be able to decompile it with a .NET decompiler. Plus, you don't need a decompiler - the [source code is available on GitHub]( https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicebackup2.c).

You should be able to run `idevicebackup2.exe --help`. This will give you an overview of how it works. You could then use [Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.8) to start idevicebackup2 from a command line application.

**Comment by qmfrederik** [comment]
@NehaBector I'm going to go ahead and close this issue, as 1. what you are asking is out of scope for this project and 2. I gave you hints on how to get started - either port idevicebackup2 to C# yourself, or invoke idevicebackup2 using Process.Start.
