### ISSUE TITLE
afc_read_directory returns InvalidArg

### ISSUE THREAD

**Issue by deakjahn** [libimobiledevice-win32/imobiledevice-net#9]
```
ReadOnlyCollection<string> FileListPtr;
var result = afc.afc_read_directory(AfcClient, DirectoryPath, out FileListPtr);
```

Returns AfcError.InvalidArg. Both AfcClient and DirectoryPath are valid. The extra condition in afc.c is a bit suspicious:

```
if (!client || !path || !directory_information || (directory_information && *directory_information))
  return AFC_E_INVALID_ARG;
```

**Comment by qmfrederik** [comment]
That's strange, I have code which executes afc_read_directory and which works correctly.

Do you have a small repro I could use to reproduce the issue? Which version of imobiledevice-net are you using?

**Comment by deakjahn** [comment]
Contrary to what I thought, AfcClient wasn't valid. It wasn't obvious at first while debugging... The reason was that I had used the static

`var afc = LibiMobileDevice.Instance.Afc;`

to obtain the pointer to the Api. When I switched to

`var afc = lockdownService.Api.Afc;`

it started to work. I don't know if this is intended or a bug.

**Comment by qmfrederik** [comment]
I don't think that should make a difference; the afc variable you have really is just a proxy for all the P/Invoke calls and it doesn't keep any state.

I'm guessing perhaps the `AfClientHandle` has an incorrect value? If you want to investigate further, let me know how you create the `AfcClientHandle` and we can have a look.

**Comment by deakjahn** [comment]
It was simply zero but a cursory look with the VS debugger didn't reveal it.

Very simple, really:

```
var lockdown = Handle.Api.Lockdown;
if (lockdownClient.IsInvalid && lockdown.lockdownd_client_new_with_handshake(Handle, out lockdownClient, "XXX") != LockdownError.Success)
  return false;
if (lockdownService.IsInvalid && lockdown.lockdownd_start_service(lockdownClient, "com.apple.afc", out lockdownService) != LockdownError.Success)
  return false;

var afc = lockdownService.Api.Afc;
if (AfcClient.IsInvalid && afc.afc_client_new(Handle, lockdownService, out AfcClient) != AfcError.Success)
  return false;
```

**Comment by qmfrederik** [comment]
@deakjahn I'm cleaning up some old issues on the repo and it seems you find a way to make this work, so I'm closing this issue for now. Thanks for using imobiledevice-net!
